version: "3.7"

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: fullstack
    ports:
      - 27017:27017
    volumes:
      - ./json:/json
      - data:/data/db

volumes:
  data:
